### PR TITLE
add admissionReviewVersions

### PR DESCRIPTION
**Pull request by rphillips**
add missing admissionReviewVersions

### CODE REVIEW

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Comment by jrvaldes** [comment]
@rphillips  do we need to backport this?

**Comment by rphillips** [comment]
not yet... we will if we backport the entire feature. I don't believe we have to backport the entire feature yet.

**Comment by rphillips** [comment]
/override ci/prow/e2e-aws

via discussion on slack

**Pull request merged**
